# Generated by Django 6.0.3 on 2026-03-07 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_add_message_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='chat_message_room_time_idx',
        ),
    ]
