# Generated by Django 6.0.3 on 2026-03-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_message_chat_message_room_time_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='protected',
            field=models.BooleanField(default=False),
        ),
    ]
