# Generated by Django 6.0.4 on 2026-04-17 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_message_reply_to_messagereaction_messagereadby'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='messagereaction',
            new_name='chat_msgreact_idx',
            old_name='chat_msgreaction_msg_reaction_idx',
        ),
    ]
