# Generated by Django 6.0.4 on 2026-04-19 22:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_rename_chat_msgreaction_msg_reaction_idx_chat_msgreact_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='tracked_by',
            field=models.ManyToManyField(blank=True, related_name='tracked_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
