# Generated by Django 6.0.3 on 2026-04-05 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('task', 'Task'), ('book', 'Book'), ('event', 'Event'), ('message', 'Message'), ('decision', 'Decision')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField()),
                ('url', models.CharField(max_length=500)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='feed_item_timestamp_idx'), models.Index(fields=['content_type', 'object_id'], name='feed_item_content_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('task', 'Task'), ('book', 'Book'), ('event', 'Event'), ('message', 'Message'), ('decision', 'Decision')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('read_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'content_type'], name='readstatus_user_content_idx')],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
