# Generated by Django 6.0.3 on 2026-04-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readstatus',
            name='content_type',
            field=models.CharField(choices=[('post', 'Post'), ('task', 'Task'), ('book', 'Book'), ('event', 'Event'), ('message', 'Message'), ('decision', 'Decision'), ('membership', 'Membership'), ('transaction', 'Transaction')], max_length=20),
        ),
    ]
