# Generated by Django 6.0.3 on 2026-04-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_readstatus_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('was_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-deleted_at'],
                'indexes': [models.Index(fields=['deleted_at'], name='deleted_user_deleted_at_idx')],
            },
        ),
    ]
