# Generated by Django 6.0.3 on 2026-04-05 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_deleteduser'),
        ('obywatele', '0012_alter_uzytkownik_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReputationLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('reputation_at_loss', models.SmallIntegerField()),
                ('required_reputation', models.SmallIntegerField()),
                ('lost_at', models.DateTimeField(auto_now_add=True)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obywatele.uzytkownik')),
            ],
            options={
                'ordering': ['-lost_at'],
                'indexes': [models.Index(fields=['lost_at'], name='reputation_loss_lost_at_idx')],
            },
        ),
    ]
