# Generated by Django 6.0.3 on 2026-04-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_reputationloss'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='deleteduser',
            name='deleted_user_deleted_at_idx',
        ),
        migrations.DeleteModel(
            name='DeletedUser',
        ),
        migrations.RemoveIndex(
            model_name='reputationloss',
            name='reputation_loss_lost_at_idx',
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='content_type',
            field=models.CharField(choices=[('post', 'Post'), ('task', 'Task'), ('book', 'Book'), ('event', 'Event'), ('message', 'Message'), ('decision', 'Decision'), ('citizen', 'Citizen Activity')], max_length=20),
        ),
        migrations.AlterField(
            model_name='readstatus',
            name='content_type',
            field=models.CharField(choices=[('post', 'Post'), ('task', 'Task'), ('book', 'Book'), ('event', 'Event'), ('message', 'Message'), ('decision', 'Decision'), ('citizen', 'Citizen Activity')], max_length=20),
        ),
        migrations.DeleteModel(
            name='ReputationLoss',
        ),
    ]
