# Generated by Django 6.0.4 on 2026-04-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_postcategory_post_category'),
        ('home', '0006_onboardingprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingprogress',
            name='step1_read',
        ),
        migrations.RemoveField(
            model_name='onboardingprogress',
            name='step2_discussed',
        ),
        migrations.RemoveField(
            model_name='onboardingprogress',
            name='step3_voted',
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='docs_read',
            field=models.ManyToManyField(blank=True, related_name='+', to='board.post'),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='step_argued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='step_chatted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingprogress',
            name='step_voted',
            field=models.BooleanField(default=False),
        ),
    ]
