# Generated by Django 6.0.4 on 2026-04-18 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0007_postcategory_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboarding_category', models.ForeignKey(blank=True, help_text='Posts from this category can be marked as required reading', null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.postcategory', verbose_name='Onboarding category')),
                ('onboarding_posts', models.ManyToManyField(blank=True, help_text='Posts the user must read during onboarding', to='board.post', verbose_name='Onboarding documents')),
            ],
            options={
                'verbose_name': 'Site settings',
            },
        ),
    ]
