# Generated by Django 6.0.3 on 2026-03-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0011_alter_uzytkownik_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='phone',
            field=models.CharField(blank=True, help_text='Preferred communicator or phone number', max_length=72, null=True, verbose_name='Phone number'),
        ),
    ]
