# Generated by Django 6.0.3 on 2026-04-05 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0012_alter_uzytkownik_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('new_candidate', 'New Candidate'), ('user_activated', 'User Activated'), ('user_blocked', 'User Blocked')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='obywatele.uzytkownik')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='citizen_activity_timestamp_idx'), models.Index(fields=['activity_type'], name='citizen_activity_type_idx')],
            },
        ),
    ]
