# Generated by Django 6.0.3 on 2026-04-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0013_citizenactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenactivity',
            name='activity_type',
            field=models.CharField(choices=[('new_candidate', 'New Candidate'), ('user_activated', 'User Activated')], max_length=20),
        ),
    ]
