# Generated by Django 6.0.3 on 2026-04-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0015_alter_citizenactivity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='email_notifications_chat',
            field=models.BooleanField(default=True, help_text='Receive notifications about new chat messages', verbose_name='Chat notifications'),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='email_notifications_glosowania',
            field=models.BooleanField(default=True, help_text='Receive notifications about law proposals and voting', verbose_name='Voting notifications'),
        ),
        migrations.AddField(
            model_name='uzytkownik',
            name='email_notifications_obywatele',
            field=models.BooleanField(default=True, help_text='Receive notifications about new citizens and membership requests', verbose_name='Citizenship notifications'),
        ),
    ]
