# Generated by Django 6.0.4 on 2026-04-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obywatele', '0018_uzytkownik_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='email_notifications_chat_participated',
            field=models.BooleanField(default=False, help_text='Receive notifications only for chat rooms where I have participated', verbose_name='Chat notifications — participated only'),
        ),
    ]
